# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e9b72baec14e5414c140fad81d565e72e7b9d13b187e08e969a5e8ed902cce1e9c3d2550053d12eb0efd037babb5bf15199e5f03770148b15c49ef4058252edf

test:
  secret_key_base: 51d867f41968cdbb8c194009fdb46aeaa01fb7da5dc2bc961ca2445e52c6072a9216c905ec73bd1d9663b077a28554a2327ae7de915d60111a6a5bdd13dc08a3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
